### ISSUE TITLE
terraspace plan fails in ci

### ISSUE THREAD

**Issue by olizilla** [web3-storage/ipfs-elastic-provider#33]
https://github.com/elastic-ipfs/infrastructure/actions/runs/5181165258/jobs/9336299967#step:8:112

```sh
Run echo "AWS_REGION=${AWS_REGION}"
  echo "AWS_REGION=${AWS_REGION}"
  echo "TS_ENV=${TS_ENV}"          
  echo "STACK=${STACK}"
  AWS_REGION=${AWS_REGION} TS_ENV=${TS_ENV} terraspace plan "${STACK}" --auto
  shell: /usr/bin/bash -e {0}
  env:
    AWS_REGION: us-west-[2](https://github.com/elastic-ipfs/infrastructure/actions/runs/5181165258/jobs/9336299967#step:8:2)
    TF_IN_AUTOMATION: 1
    ASDF_DIR: /home/runner/.asdf
    ASDF_DATA_DIR: /home/runner/.asdf
    AWS_DEFAULT_REGION: us-west-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    TS_ENV: prod
    STACK: peer
AWS_REGION=us-west-2
TS_ENV=prod
STACK=peer
WARN: Unable to find line number. Fallback and print out full backtrace.
/home/runner/.asdf/installs/ruby/[3](https://github.com/elastic-ipfs/infrastructure/actions/runs/5181165258/jobs/9336299967#step:8:3).1.1/lib/ruby/gems/3.1.0/gems/tilt-2.2.0/lib/tilt/template.rb:10[4](https://github.com/elastic-ipfs/infrastructure/actions/runs/5181165258/jobs/9336299967#step:8:4):in `render'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/render_me_pretty-0.8.4/lib/render_me_pretty/erb.rb:91:in `render'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/render_me_pretty-0.8.4/lib/render_me_pretty.rb:11:in `result'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/erb/render.rb:9:in `build'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/strategy/tfvar/tfvars.rb:4:in `run'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/render_me_pretty-0.8.4/lib/render_me_pretty/erb/base_handler.rb:24:in `pretty_trace': undefined method `-' for nil:NilClass (NoMethodError)
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/strategy/tfvar.rb:17:in `block in run'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/strategy/tfvar.rb:11:in `each'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/strategy/tfvar.rb:11:in `run'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/perform.rb:31:in `compile_tfvars'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/dependency/resolver.rb:12:in `block in resolve'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/dirs_concern.rb:18:in `block in with_each_mod'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/dirs_concern.rb:1[5](https://github.com/elastic-ipfs/infrastructure/actions/runs/5181165258/jobs/9336299967#step:8:5):in `each'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/dirs_concern.rb:15:in `with_each_mod'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/dependency/resolver.rb:10:in `resolve'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/builder.rb:3[6](https://github.com/elastic-ipfs/infrastructure/actions/runs/5181165258/jobs/9336299967#step:8:6):in `resolve_dependencies'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.[7](https://github.com/elastic-ipfs/infrastructure/actions/runs/5181165258/jobs/9336299967#step:8:7)/lib/terraspace/builder.rb:30:in `run'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/cli/commander.rb:9:in `run'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/cli.rb:155:in `plan'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/command.rb:61:in `dispatch'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/base.rb:4[8](https://github.com/elastic-ipfs/infrastructure/actions/runs/5181165258/jobs/9336299967#step:8:8)5:in `start'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/cli/concern.rb:65:in `start'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/exe/terraspace:14:in `<top (required)>'
/home/runner/.asdf/installs/ruby/3.1.1/bin/terraspace:25:in `load'
/home/runner/.asdf/installs/ruby/3.1.1/bin/terraspace:25:in `<main>'

      top, bottom = [error_line_number-context-1, 0].max, error_line_number+context-1
                                      ^
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/render_me_pretty-0.8.4/lib/render_me_pretty/erb/base_handler.rb:11:in `handle'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/render_me_pretty-0.8.4/lib/render_me_pretty/erb.rb:11[9](https://github.com/elastic-ipfs/infrastructure/actions/runs/5181165258/jobs/9336299967#step:8:9):in `handle_exception'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/render_me_pretty-0.8.4/lib/render_me_pretty/erb.rb:97:in `rescue in render'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/render_me_pretty-0.8.4/lib/render_me_pretty/erb.rb:85:in `render'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/render_me_pretty-0.8.4/lib/render_me_pretty.rb:11:in `result'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/erb/render.rb:9:in `build'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/strategy/tfvar/tfvars.rb:4:in `run'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/strategy/tfvar.rb:17:in `block in run'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/strategy/tfvar.rb:11:in `each'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/strategy/tfvar.rb:11:in `run'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/perform.rb:31:in `compile_tfvars'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/dependency/resolver.rb:12:in `block in resolve'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/dirs_concern.rb:18:in `block in with_each_mod'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/dirs_concern.rb:15:in `each'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/dirs_concern.rb:15:in `with_each_mod'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/dependency/resolver.rb:[10](https://github.com/elastic-ipfs/infrastructure/actions/runs/5181165258/jobs/9336299967#step:8:10):in `resolve'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/builder.rb:36:in `resolve_dependencies'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/builder.rb:30:in `run'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/cli/commander.rb:9:in `run'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/cli.rb:155:in `plan'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/command.rb:61:in `dispatch'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/cli/concern.rb:65:in `start'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/exe/terraspace:14:in `<top (required)>'
	from /home/runner/.asdf/installs/ruby/3.1.1/bin/terraspace:25:in `load'
	from /home/runner/.asdf/installs/ruby/3.1.1/bin/terraspace:25:in `<main>'
/home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/tilt-2.2.0/lib/tilt/template.rb:104:in `render': uninitialized constant Tilt::Template::EMPTY_HASH (NameError)

      evaluate(scope || Object.new, locals || EMPTY_HASH, &block)
                                              ^^^^^^^^^^
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/render_me_pretty-0.8.4/lib/render_me_pretty/erb.rb:91:in `render'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/render_me_pretty-0.8.4/lib/render_me_pretty.rb:[11](https://github.com/elastic-ipfs/infrastructure/actions/runs/5181165258/jobs/9336299967#step:8:11):in `result'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/erb/render.rb:9:in `build'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/strategy/tfvar/tfvars.rb:4:in `run'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/strategy/tfvar.rb:17:in `block in run'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/strategy/tfvar.rb:11:in `each'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/strategy/tfvar.rb:11:in `run'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/perform.rb:31:in `compile_tfvars'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/dependency/resolver.rb:[12](https://github.com/elastic-ipfs/infrastructure/actions/runs/5181165258/jobs/9336299967#step:8:12):in `block in resolve'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/dirs_concern.rb:18:in `block in with_each_mod'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/dirs_concern.rb:15:in `each'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/compiler/dirs_concern.rb:15:in `with_each_mod'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/dependency/resolver.rb:10:in `resolve'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/builder.rb:36:in `resolve_dependencies'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/builder.rb:30:in `run'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/cli/commander.rb:9:in `run'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/cli.rb:155:in `plan'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/command.rb:61:in `dispatch'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/lib/terraspace/cli/concern.rb:65:in `start'
	from /home/runner/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/terraspace-1.1.7/exe/terraspace:[14](https://github.com/elastic-ipfs/infrastructure/actions/runs/5181165258/jobs/9336299967#step:8:14):in `<top (required)>'
	from /home/runner/.asdf/installs/ruby/3.1.1/bin/terraspace:[25](https://github.com/elastic-ipfs/infrastructure/actions/runs/5181165258/jobs/9336299967#step:8:26):in `load'
	from /home/runner/.asdf/installs/ruby/3.1.1/bin/terraspace:25:in `<main>'
Error: Process completed with exit code 1.
```

**Comment by olizilla** [comment]
installing the deps with asdf and running locally works. I've tried deleting the tool cache in ci and re-run, but it still fails. It was working yesterday! what changed?

**Comment by olizilla** [comment]
now it magically works...
